### PR TITLE
forge: support 1.7.x install_profile.json

### LINKED ISSUE #174: Cannot find version in older FORGE_INSTALLER
```
[mc-image-helper] 15:03:24.262 ERROR : 'install-forge' command failed. Version is 1.25.16
 me.itzg.helpers.errors.GenericException: Failed to locate version from provided installer file
        at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:88)
        at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:84)
        at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:16)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:132)
[init] ERROR failed to install Forge given installer /modpacks/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar
```

### PR DESCRIPTION
**Pull request by itzg**
Resolves #174 

cc @kevinkjt2000

### CODE REVIEW

File: src/main/java/me/itzg/helpers/forge/ForgeInstaller.java [hunk 1]
```diff
@@ -163,6 +166,37 @@ private VersionPair extractVersion(Path forgeInstaller) throws IOException {
...
+        return IoStreams.readFileFromZip(forgeInstaller, "install_profile.json", inputStream -> {
+            final ObjectNode parsed = ObjectMappers.defaultMapper()
+                .readValue(inputStream, ObjectNode.class);
+
+            final JsonNode idNode = parsed.path("versionInfo").path("id");
+            if (idNode.isTextual()) {
+                // such as "1.7.10-Forge10.13.4.1614-1.7.10"
+                final String[] idParts = idNode.asText().split("-");
+
+                if (idParts.length == 3) {
```
Comment (kevinkjt2000) [inline src/main/java/me/itzg/helpers/forge/ForgeInstaller.java:182]: Some of the forge versions only have length 2 here. 1.7.10 sure had an annoying extra bit in the filename.
Here's 1.5.2:
```json
  "versionInfo": {
    "id": "1.5.2-Forge7.8.1.738",
```

Comment (itzg) [reply src/main/java/me/itzg/helpers/forge/ForgeInstaller.java:182]: Great investigation. As I mentioned over in the issue, it would be awesome if you could PR the fix for this. Just reference the same issue as before.

Comment (kevinkjt2000) [reply src/main/java/me/itzg/helpers/forge/ForgeInstaller.java:182]:
```suggestion
                if (idParts.length == 2 || idParts.length == 3) {
```

Comment (itzg) [reply src/main/java/me/itzg/helpers/forge/ForgeInstaller.java:182]: Code suggestions can't be applied after the PR is merged. Can you create a new PR with this?
